# This workflow automates the process of creating releases, updating the CHANGELOG,
# and publishing the package to npm using release-please.

name: Release

on:
  push:
    # Trigger on push to the primary branch (usually 'main' or 'master')
    branches:
      - main
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      # Required for creating releases and pushing changes to the repository
      contents: write
      # Required for managing pull requests
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Run the release-please action
      # This action manages the version bump, CHANGELOG, and GitHub Release.
      # It creates a release Pull Request (PR) when needed, and only runs the
      # publish steps below when that PR is merged.
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: main

      # --- Conditional Publishing Steps ---
      # 2. These steps only run IF a new release was successfully created (did_release is true)

      - name: Set up Node.js for publishing
        if: ${{ steps.release.outputs.did_release }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # Configure npm authentication using the provided token secret
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies and run scripts
        if: ${{ steps.release.outputs.did_release }}
        run: |
          echo "New release created: Publishing version ${{ steps.release.outputs.version }}"
          # Use npm ci for clean and fast dependency installation in CI environments
          npm ci
          # Run the documentation generation script (docs) to ensure the package
          # being published includes the up-to-date documentation content.
          npm run docs
          # Run the fix script to ensure final code formatting and linting is applied
          npm run fix

      - name: NPM Publish
        if: ${{ steps.release.outputs.did_release }}
        run: npm publish
        env:
          # This secret is used by npm to authenticate the publish operation
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
